[package]
name = "grpc_video_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.13"
anyhow = "1.0"


prost = "0.13"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"


[build-dependencies]
tonic-build = "*"
